namespace DeSCam;

/// <summary>Descriptor for a single ChrFollowCam parameter.</summary>
public record ParamDef(
    string Name,
    uint   NodeOffset,      // offset within FollowNode for ptr-chain mode (debug EBOOT)
    string Unit,            // "rad" or "float"
    string Description,
    int    FieldOffset = 0,
    uint   DirectOffset = 0) // direct float offset within FollowNode (normal EBOOT), 0 = unknown
{
    public double Default => Defaults.TryGetValue(Name, out var v) ? v : 0.0;
    public string UnitLabel => Unit == "rad" ? "°" : "f";

    // ── Static param table ────────────────────────────────────────────────────
    public static readonly ParamDef[] All =
    [
        // DirectOffset = direct float offset in FollowNode body (normal EBOOT)
        // NodeOffset   = ptr-chain offset (debug EBOOT): FollowNode+NodeOffset+0x30 → ptr → float
        new("FovY",                           0x0050, "rad",   "Field of View Y (rad→deg)",         0, 0x050),
        new("ChrOrgOffset_X",                 0x00A0, "float", "Origin offset X [0]",                0, 0x150),
        new("ChrOrgOffset_Y",                 0x00A0, "float", "Origin offset Y [0→+up]",            0, 0x154),
        new("ChrOrgOffset_Z",                 0x00A0, "float", "Origin offset Z [0]",                0, 0x158),
        new("FulcrumDistRateByLrMoveMaxDist", 0x0190, "float", "= 0.300",                            0, 0x160),
        new("FulcrumDistRateMinByLrMove",     0x01E0, "float", "= 0.100",                            0, 0x164),
        new("FulcrumDistRateMaxByLrMove",     0x0230, "float", "= 0.990",                            0, 0x168),
        new("FulcrumDistRate",                0x0280, "float", "= 0.500",                            0, 0x16C),
        new("FulcrumDist",                    0x02D0, "float", "= 3.600",                            0, 0x170),
        new("CamDist",                        0x0320, "float", "= 4.000",                            0, 0x174),
        new("CamDistTarget",                  0x0370, "float", "= 4.000",                            0, 0x178),
        new("ChrTransChaseRate",              0x03C0, "float", "= 0.100 (dynamic)",                  0, 0x17C),
        new("ChrTransChaseRateForNormal",     0x0410, "float", "= 0.100",                            0, 0x180),
        new("ChrTransChaseRateForEscapeWall", 0x0460, "float", "= 0.150",                            0, 0x184),
        new("TargetTransChaseRate",           0x04B0, "float", "= 0.300",                            0, 0x188),
        new("TargetRotXChaseRate",            0x0500, "float", "= 0.300",                            0, 0x18C),
        new("TargetChaseRateXZ",              0x0550, "float", "= 0.100 (dynamic)",                  0, 0x190),
        new("TargetChaseRateXZForNormal",    0x05A0, "float", "= 0.100",                            0, 0x194),
        new("TargetChaseRateXZForEscapeWall",0x05F0, "float", "= 0.150",                            0, 0x198),
        new("TargetChaseRateY",               0x0640, "float", "= 0.030",                            0, 0x19C),
        new("TargetChaseRateMinAng",          0x0690, "float", "= 0.000175 rad (~0.01°)",            0, 0x1A0),
        new("TargetChaseRateMaxAng",          0x06E0, "float", "= 0.000349 rad (~0.02°)",            0, 0x1A4),
        new("TargetChaseDistRate",            0x0730, "float", "= 0.400",                            0, 0x1A8),
        new("TargetChaseRateAtLockXZ",        0x0780, "float", "= 0.400",                            0, 0x1AC),
        new("TargetChaseRateAtLockY",         0x07D0, "float", "= 0.300",                            0, 0x1B0),
        new("TargetChaseRateMinAngAtLock",    0x0820, "float", "= 0.000",                            0, 0x1B4),
        new("TargetChaseRateMaxAngAtLock",    0x0870, "float", "= 0.000",                            0, 0x1B8),
        new("TransChaseByControlEndWaitTime", 0x0000, "float", "= 0.000 [sec]",                      0, 0x1BC),
        new("TransChaseByControlEndRelTime",  0x0000, "float", "= 1.000 [sec]",                      0, 0x1C0),
        new("RotCtrlEndWaitTime",             0x0000, "float", "= 2.000 [sec]",                      0, 0x1C4),
        new("RotCtrlEndReleaseTime",          0x0000, "float", "= 1.000 [sec]",                      0, 0x1C8),
        new("RotHiSpeedRateIncTime",          0x0000, "float", "= 0.600 [sec]",                      0, 0x1CC),
        new("RotRange_MaxX",                  0x0000, "rad",   "= 70.0° max vertical",               0, 0x1D0),
        new("RotRange_MinX",                  0x0000, "rad",   "= -40.0° min vertical",              0, 0x1D4),
        new("RotRangeAtLock_MaxX",            0x0000, "rad",   "= 40.0° max vertical at lock",       0, 0x1D8),
        new("RotRangeAtLock_MinX",            0x0000, "rad",   "= -40.0° min vertical at lock",      0, 0x1DC),
        new("RotRangeLerpHeight_Begin",       0x0000, "float", "= 0.500°",                           0, 0x1E0),
        new("RotRangeLerpHeight_End",         0x0000, "float", "= 2.000°",                           0, 0x1E4),
        new("RotSpeed_X",                     0x0000, "rad",   "= 120°/sec",                         0, 0x1E8),
        new("RotSpeed_Y",                     0x0000, "rad",   "= 120°/sec",                         0, 0x1EC),
        new("RotSpeedMin_X",                  0x0000, "rad",   "= 80°/sec",                          0, 0x1F0),
        new("RotSpeedMin_Y",                  0x0000, "rad",   "= 80°/sec",                          0, 0x1F4),
        new("RotSpeedMax_X",                  0x0000, "rad",   "= 240°/sec",                         0, 0x1F8),
        new("RotSpeedMax_Y",                  0x0000, "rad",   "= 240°/sec",                         0, 0x1FC),
        new("RotHiSpeed_X",                   0x0000, "rad",   "= 260°/sec",                         0, 0x200),
        new("RotHiSpeed_Y",                   0x0000, "rad",   "= 260°/sec",                         0, 0x204),
        new("RotHiSpeedMin_X",                0x0000, "rad",   "= 180°/sec",                         0, 0x208),
        new("RotHiSpeedMin_Y",                0x0000, "rad",   "= 180°/sec",                         0, 0x20C),
        new("RotHiSpeedMax_X",                0x0000, "rad",   "= 500°/sec",                         0, 0x210),
        new("RotHiSpeedMax_Y",                0x0000, "rad",   "= 500°/sec",                         0, 0x214),
        new("OptionRotSpeedRate",             0x0000, "float", "= 0.500",                            0, 0x218),
        new("DirectPitchAng",                 0x0000, "rad",   "= 60°",                              0, 0x21C),
        new("DirectPitchRate",                0x0000, "float", "= 0.060",                            0, 0x220),
        new("LockRotChaseRate",               0x0000, "float", "= 0.300",                            0, 0x224),
        new("LockRotChasePlayAng",            0x0000, "rad",   "= 3°",                               0, 0x228),
        new("LockRotXShiftRatio",             0x0000, "float", "= 0.600",                            0, 0x22C),
        new("ForceFrontLockTime",             0x0000, "float", "= 0.300",                            0, 0x248),
        new("EscapeWallRotAddX",              0x0000, "rad",   "= 60°/sec",                          0, 0x260),
        new("EscapeWallRotAddY",              0x0000, "rad",   "= 60°/sec",                          0, 0x264),
        new("EscapeWallRotMaxX",              0x0000, "rad",   "= 240°/sec",                         0, 0x268),
        new("EscapeWallRotMaxY",              0x0000, "rad",   "= 240°/sec",                         0, 0x26C),
        new("EscapeWallRotDampRatio",         0x0000, "float", "= 0.550",                            0, 0x270),
        new("EscapeWallWingAngY",             0x0000, "rad",   "= 5°",                               0, 0x274),
        new("EscapeWallWingLen",              0x0000, "float", "= 2.000 [m]",                        0, 0x278),
        new("EscapeWallWingRadius",           0x0000, "float", "= 0.010 [m]",                        0, 0x27C),
        new("EscapeWallWingSeparate",         0x0000, "float", "= 0.340 [m]",                        0, 0x280),
        new("CamModeParamLerpRate",           0x0000, "float", "= 0.100",                            0, 0x294),
    ];

    static readonly Dictionary<string, double> Defaults = new()
    {
        ["FovY"]                           = 43.0, // 0.75 rad default (normal EBOOT)
        ["ChrOrgOffset_X"]                 = 0.0,
        ["ChrOrgOffset_Y"]                 = 1.42,
        ["ChrOrgOffset_Z"]                 = 0.0,
        ["FulcrumDistRateByLrMoveMaxDist"] = 0.3,
        ["FulcrumDistRateMinByLrMove"]     = 0.1,
        ["FulcrumDistRateMaxByLrMove"]     = 0.99,
        ["FulcrumDistRate"]                = 0.5,
        ["FulcrumDist"]                    = 3.6,
        ["CamDist"]                        = 4.0,
        ["CamDistTarget"]                  = 4.0,
        ["ChrTransChaseRate"]              = 0.1,
        ["ChrTransChaseRateForNormal"]     = 0.1,
        ["ChrTransChaseRateForEscapeWall"] = 0.15,
        ["TargetTransChaseRate"]           = 0.3,
        ["TargetRotXChaseRate"]            = 0.3,
        ["TargetChaseRateXZ"]              = 0.1,
        ["TargetChaseRateXZForNormal"]     = 0.1,
        ["TargetChaseRateXZForEscapeWall"] = 0.15,
        ["TargetChaseRateY"]               = 0.03,
        ["TargetChaseRateMinAng"]          = 0.000175,
        ["TargetChaseRateMaxAng"]          = 0.000349,
        ["TargetChaseDistRate"]            = 0.4,
        ["TargetChaseRateAtLockXZ"]        = 0.4,
        ["TargetChaseRateAtLockY"]         = 0.3,
        ["TargetChaseRateMinAngAtLock"]    = 0.0,
        ["TargetChaseRateMaxAngAtLock"]    = 0.0,
        ["TransChaseByControlEndWaitTime"] = 0.0,
        ["TransChaseByControlEndRelTime"]  = 1.0,
        ["RotCtrlEndWaitTime"]             = 2.0,
        ["RotCtrlEndReleaseTime"]          = 1.0,
        ["RotHiSpeedRateIncTime"]          = 0.6,
        ["RotRange_MaxX"]                  = 70.0,
        ["RotRange_MinX"]                  = -40.0,
        ["RotRangeAtLock_MaxX"]            = 40.0,
        ["RotRangeAtLock_MinX"]            = -40.0,
        ["RotRangeLerpHeight_Begin"]       = 0.5,
        ["RotRangeLerpHeight_End"]         = 2.0,
        ["RotSpeed_X"]                     = 120.0,
        ["RotSpeed_Y"]                     = 120.0,
        ["RotSpeedMin_X"]                  = 80.0,
        ["RotSpeedMin_Y"]                  = 80.0,
        ["RotSpeedMax_X"]                  = 240.0,
        ["RotSpeedMax_Y"]                  = 240.0,
        ["RotHiSpeed_X"]                   = 260.0,
        ["RotHiSpeed_Y"]                   = 260.0,
        ["RotHiSpeedMin_X"]                = 180.0,
        ["RotHiSpeedMin_Y"]                = 180.0,
        ["RotHiSpeedMax_X"]                = 500.0,
        ["RotHiSpeedMax_Y"]                = 500.0,
        ["OptionRotSpeedRate"]             = 0.5,
        ["DirectPitchAng"]                 = 60.0,
        ["DirectPitchRate"]                = 0.06,
        ["LockRotChaseRate"]               = 0.3,
        ["LockRotChasePlayAng"]            = 3.0,
        ["LockRotXShiftRatio"]             = 0.6,
        ["ForceFrontLockTime"]             = 0.3,
        ["EscapeWallRotAddX"]              = 60.0,
        ["EscapeWallRotAddY"]              = 60.0,
        ["EscapeWallRotMaxX"]              = 240.0,
        ["EscapeWallRotMaxY"]              = 240.0,
        ["EscapeWallRotDampRatio"]         = 0.55,
        ["EscapeWallWingAngY"]             = 5.0,
        ["EscapeWallWingLen"]              = 2.0,
        ["EscapeWallWingRadius"]           = 0.01,
        ["EscapeWallWingSeparate"]         = 0.34,
        ["CamModeParamLerpRate"]           = 0.1,
    };
}
